import { Layout } from "@/components/layout/Layout";
import { 
  Leaf, 
  Cloud, 
  Cpu, 
  Recycle, 
  TrendingDown, 
  Lightbulb,
  ArrowLeft
} from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

const Blog = () => {
  return (
    <Layout>
      {/* Hero */}
      <section className="hero-section">
        <div className="page-container py-12 sm:py-16">
          <Button asChild variant="ghost" size="sm" className="mb-6">
            <Link to="/">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Link>
          </Button>
          
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-lg bg-accent/10 text-accent flex items-center justify-center">
              <Leaf className="h-5 w-5" />
            </div>
            <span className="text-sm font-medium text-muted-foreground">Sustainability Blog</span>
          </div>
          
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-4 max-w-3xl">
            The Sustainability Challenge in Computer Science
          </h1>
          
          <p className="text-muted-foreground max-w-2xl">
            Exploring how the computing industry can address environmental concerns through sustainable practices and green technology.
          </p>
        </div>
      </section>

      {/* Article Content */}
      <article className="page-container py-12 sm:py-16">
        <div className="max-w-3xl mx-auto">
          {/* Introduction */}
          <section className="mb-12">
            <h2 className="text-2xl font-bold mb-4">Introduction</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              As computer science continues to transform every aspect of modern life, it brings with it a significant 
              environmental footprint that demands our attention. From the energy consumed by data centres to the 
              electronic waste generated by obsolete devices, the technology sector faces urgent sustainability challenges.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              This blog explores the environmental impact of computing, examines current initiatives to address these 
              issues, and reflects on the responsibility of computer scientists to develop sustainable solutions.
            </p>
          </section>

          {/* Key Statistics Card */}
          <div className="card-base bg-accent/5 border-accent/20 mb-12">
            <div className="flex items-start gap-4">
              <TrendingDown className="h-6 w-6 text-accent flex-shrink-0 mt-1" />
              <div>
                <h3 className="font-semibold mb-2">Key Environmental Facts</h3>
                <ul className="text-muted-foreground space-y-2 text-sm">
                  <li>• Data centres consume approximately 1-2% of global electricity</li>
                  <li>• The ICT sector accounts for 2-4% of global carbon emissions</li>
                  <li>• E-waste is the fastest-growing waste stream globally</li>
                  <li>• Training a single AI model can emit as much CO₂ as five cars over their lifetime</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Role of CS */}
          <section className="mb-12">
            <h2 className="text-2xl font-bold mb-4">The Role of Computer Science</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Computer science sits at a unique crossroads—it contributes to environmental challenges but also holds 
              the key to solving them. Programmers and software engineers make decisions every day that impact energy 
              consumption, from algorithm efficiency to infrastructure choices.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              More importantly, computing provides the tools for monitoring climate change, optimising resource usage, 
              and developing renewable energy systems. The discipline has both the responsibility and capability to 
              lead the transition to sustainable technology.
            </p>
          </section>

          {/* Real-World Examples */}
          <section className="mb-12">
            <h2 className="text-2xl font-bold mb-6">Real-World Initiatives</h2>
            
            <div className="grid gap-6">
              <div className="card-base">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center flex-shrink-0">
                    <Cloud className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Green Cloud Computing</h3>
                    <p className="text-muted-foreground text-sm leading-relaxed">
                      Major cloud providers like Google, Microsoft, and Amazon are investing heavily in renewable energy 
                      to power their data centres. Google has been carbon-neutral since 2007 and aims to run on carbon-free 
                      energy 24/7 by 2030. These efforts demonstrate that large-scale computing can be sustainable.
                    </p>
                  </div>
                </div>
              </div>

              <div className="card-base">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center flex-shrink-0">
                    <Cpu className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Energy-Efficient AI</h3>
                    <p className="text-muted-foreground text-sm leading-relaxed">
                      Researchers are developing more efficient machine learning models that require less computational 
                      power. Techniques like model pruning, knowledge distillation, and efficient architectures are 
                      reducing the environmental cost of AI while maintaining performance.
                    </p>
                  </div>
                </div>
              </div>

              <div className="card-base">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center flex-shrink-0">
                    <Recycle className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Circular Economy in Tech</h3>
                    <p className="text-muted-foreground text-sm leading-relaxed">
                      Companies are embracing circular economy principles, designing products for longevity, repairability, 
                      and recyclability. Apple's use of recycled materials and modular repair programs, along with 
                      initiatives like Fairphone, show how hardware can become more sustainable.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Personal Reflection */}
          <section className="mb-12">
            <div className="card-base border-l-4 border-l-accent">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-lg bg-accent/10 text-accent flex items-center justify-center flex-shrink-0">
                  <Lightbulb className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="font-semibold mb-3">Personal Reflection</h3>
                  <div className="text-muted-foreground space-y-3 text-sm leading-relaxed">
                    <p>
                      Researching this topic has fundamentally changed how I view my role as a computer science student. 
                      I now understand that every line of code, every algorithm choice, and every system design decision 
                      carries environmental implications.
                    </p>
                    <p>
                      Going forward, I am committed to considering sustainability in my technical decisions—whether 
                      that means choosing efficient algorithms, optimising code to reduce server load, or advocating 
                      for green computing practices in my future workplace.
                    </p>
                    <p>
                      The sustainability challenge is not just an environmental issue; it is a computing challenge 
                      that our generation of computer scientists must solve.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Conclusion */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Conclusion</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The sustainability challenge in computer science is urgent but not insurmountable. Through conscious 
              design choices, technological innovation, and industry-wide commitment to environmental responsibility, 
              the computing sector can become a leader in the fight against climate change.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              As future computer scientists, we have both the opportunity and the obligation to build technology 
              that serves humanity without compromising the planet. The code we write today will shape the 
              environmental legacy we leave for future generations.
            </p>
          </section>
        </div>
      </article>
    </Layout>
  );
};

export default Blog;
